config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "about", to: "home#about"
  get "recycling", to: "home#recycling"
  get "lifestyle", to: "home#lifestyle"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/home.html.erb
<section class="u-py-100 u-h-100vh u-flex-center main-bg-back-4" style="background-color:#F6F9FC">
   <div class="container">
      <div class="row">
         <div class="col-lg-8 mx-auto">
            <h1 class="text-center display-3 u-fw-600 hero-text">Subscribe to minimalism</h1>
            <p class="text-center u-fs-22 u-lh-1_7 u-py-40">Own less and live life on the go. Spend less time buying expensive products that deperciate in value and spend more time experiencing life.</p>
            <div class="col-12 text-center">
            <button type="submit" class="btn btn-green ">
               <%= link_to 'Subscribe Now', new_user_registration_path %>        
            </button>
            </div>
         </div>
      </div>
   </div>
</section>

<section id="about">
<div class="container">
   <div class="row align-items-center">
      <div class="col-lg-5 btn-rounded text-center">
         <%=image_tag("seo/relax.jpg", alt: "", class: "plant-image")%>
      </div>
      <div class="col-lg-6 ml-auto">
         <h2 class="">
            Own less. Stress less. Live more.
         </h2>
         <div class="u-h-4 u-w-50 bg-primary rounded mt-4 mb-5"></div>
         <p class="mb-5">
            Ever wonder what freedom feels like? Minimalism can assist you in finding real freedom. Freedom from fear. Freedom from stress. Freedom from unnecessary headaches. Freedom from feeling like life is holding you down. Freedom from none stop consumerism. Minimalism allows you to be free and to be yourself.
         </p>
         <button type="submit" class="btn btn-green ">
            <%= link_to 'Subscribe Now', new_user_registration_path %>        
         </button>
      </div>
   </div>
</div>
</section>

<section class="u-py-100 u-h-100vh u-flex-center main-bg-back-5" style="background-color:#F6F9FC">
   <div class="container">
      <div class="row">
         <div class="col-lg-5 ml-auto mt-5 mb-4">
            <h2 class="text-white u-mb-30 text-right">
               Joining our recycling <br>program is easy and FREE!
            </h2>
            <p class="text-white text-right">
               More U.S. cities today are stopping their recycling programs or don't have a recycling program that actually helps reduce waste and helps the environment. We're in the midst of a climate crisis and we need more recycling programs that actaully work. We want to help change that.
            </p>
         </div>
      </div>
      <div class="col-12 text-right">
         <button type="submit" class="btn btn-green ">
            Learn More
         </button>
      </div>

   </section>


   <section id="features" class="bg-light1">
      <div class="container">
         <h3 class="u-mb-30 text-center">
            Why HomeNows?
         </h3>
         <div class="row text-center">
            <div class="col-md-4 u-mt-30">
               <div class="bg-white px-5 u-py-50 u-h-100p rounded">

                  <h4 class="u-fs-26 u-my-35">
                     It's Free
                  </h4>
                  <p class="mb-0">
                     Signing up to our recycling program cost absolutely nothing. Anyone can sign up at anytime.
                  </p>
               </div>
            </div>
            <div class="col-md-4 u-mt-30">
               <div class="bg-white px-5 u-py-50 u-h-100p rounded">

                  <h4 class="u-fs-26 u-my-35">
                     Free Rewards
                  </h4>
                  <p class="mb-0">
                     Earn rewards for being a good human being. Help take care of your planet and be rewarded. 
                  </p>
               </div>
            </div>
            <div class="col-md-4 u-mt-30">
               <div class="bg-white px-5 u-py-50 u-h-100p rounded">

                  <h4 class="u-fs-26 u-my-35">
                     Mission Driven
                  </h4>
                  <p class="mb-0">
                     We're a mission driven company focused on opening people up to a different type of lifestyle.
                  </p>
               </div>
            </div>
         </div>
      </div>
   </section>

   <section class="u-py-100 u-h-100vh u-flex-center main-bg-back-6" style="background-color:#F6F9FC">
   <div class="container">
      <div class="row">
         <div class="col-lg-8 mx-auto">
            <h2 class="text-white text-center">
               Live life on the go.
            </h2>
            <p class="text-white text-center">
            Owning furniture is a thing of the past.
            </p>
         </div>
      </div>
      <div class="col-12 text-center">
         <button type="submit" class="btn btn-green ">
            Learn More
         </button>
      </div>
   </section>

   <section class="main-bg-back-1">
      <div class="container">
         <div class="row align-items-center">
            <div class="col-lg-6">
               <h2 class="h1 text-white">
                  How the <span class="color-primary">Recycling</span> Program Works
               </h2>
               <div class="u-h-4 u-w-50 bg-primary rounded mt-4 mb-5"></div>
               <h2 class="text-white">
                  How to get started?
               </h2>
               <ul class="list-unstyled u-fw-600 u-lh-2">
                  <li>
                     <i class="fa fa-check mr-2 color-primary"></i>
                     Order a recycling bin free from us or pick a bin up at bin spot around your city.
                  </li>
                  <li>
                     <i class="fa fa-check mr-2 color-primary"></i>
                     Create an account with us.
                  </li>
                  <li>
                     <i class="fa fa-check mr-2 color-primary"></i>
                     Provide the necessary information needed in order for us to pick up your plastic.
                  </li>
                  <li>
                     <i class="fa fa-check mr-2 color-primary"></i>
                     Schedule your pick up dates and pick up locations. Our recyclers will come by and pick up your plastic.
                  </li>
               </ul>
            </div>
            <div class="col-lg-6 pl-lg-5 ml-auto text-center">
               <%=image_tag("seo/iphonemockup.png", alt: "", class: "plant-image")%>
            </div>
         </div>
      </div>
   </section>

      <section id="pricing" class="bg-light1 u-py-100">
         <div class="container text-center">
            <div class="row">
               <div class="col-12">
                  <h2 class="h1">Monthly Pricing Plans</h2>
                  <div class="u-h-4 u-w-50 bg-green rounded mt-4 u-mb-20 mx-auto"></div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-4 mt-5">
                  <div class="bg-white rounded u-pb-20">
                     <h4 class="m-0 py-4">
                        Recycling
                     </h4>
                     <hr class="m-0">
                     <h2 class="u-fs-60 u-fw-600 u-py-35 text-green"><sup class="u-fs-20">$</sup>0.00</h2>
                     <hr class="m-0">
                     <ul class="list-unstyled u-py-40 u-lh-2">
                        <li>Free bin</li>
                        <li>Weekly recycling</li>
                        <li>Up to 1 reward per month</li>
                        <li>Not eligible for 3d-printer</li>
                     </ul>
                     <hr class="m-0">
                     <div class="u-py-40">
                        <button type="submit" class="btn btn-green ">
                           <%= link_to 'Subscribe', new_user_registration_path %>       
                        </button>
                     </div>
                  </div>
               </div>
               <div class="col-md-4 mt-5">
                  <div class="bg-gray-v2 rounded u-pb-20">
                     <h4 class="m-0 py-4">
                        Recycling +
                     </h4>
                     <hr class="m-0">
                     <h2 class="u-fs-60 u-fw-600 u-py-35 text-green"><sup class="u-fs-20">$</sup>4.99</h2>
                     <hr class="m-0">
                     <ul class="list-unstyled u-py-40 u-lh-2">
                        <li>Free bin</li>
                        <li>Weekly recycling</li>
                        <li>Up to 4 rewards per month</li>
                        <li>Eligible for 3d-printer</li>
                     </ul>
                     <hr class="m-0">
                     <div class="u-py-40">
                        <button type="submit" class="btn btn-green ">
                           <%= link_to 'Subscribe', new_user_registration_path %>       
                        </button>
                     </div>
                  </div>
               </div>
               <div class="col-md-4 mt-5">
                  <div class="bg-white rounded u-pb-20">
                     <h4 class="m-0 py-4">
                        Lifestyle
                     </h4>
                     <hr class="m-0">
                     <h2 class="u-fs-60 u-fw-600 u-py-35 text-green"><sup class="u-fs-20">$</sup>199.99</h2>
                     <hr class="m-0">
                     <ul class="list-unstyled u-py-40 u-lh-2">
                        <li>Weekly recycling</li>
                        <li>Up to 4 rewards per month</li>
                        <li>Eligible for 3d-printer</li>
                        <li>Rent furniture and other necessities</li>
                     </ul>
                     <hr class="m-0">
                     <div class="u-py-40">
                        <button type="submit" class="btn btn-green ">
                           <%= link_to 'Subscribe', new_user_registration_path %>       
                        </button>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="footer-bg-back">
<div class="container">
   <div class="row">
      <div class="col-12">
         <div class="bg-black box-shadow-v1 rounded p-5">
            <h2 class="h1 text-center text-white">
               Subscribe to Our Newsletter
            </h2>
            <form class="form-inline justify-content-center my-5 subsribe-rounded">
               <div class="form-group">
                  <input type="email" class="form-control px-4 u-rounded-50 u-h-55" placeholder="Enter your email address">
               </div>
               <button type="submit" class="btn btn-rounded btn-green u-h-55">
               Subscribe Now
               </button>
            </form>
         </div>
      </div>
      <div class="col-12 text-center u-py-60">
          <h2 class="logo-brand-footer">HomeNows</h2>
         <ul class="list-inline social social-rounded mt-4">
            <li class="list-inline-item">
               <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="list-inline-item">
               <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="list-inline-item">
               <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
         </ul>
      </div>
   </div>
   <div class="row align-items-center" style="border-top:1px solid #c3f4df;color:#c3f4df">
      <div class="col-lg-6 py-4 text-center text-lg-left">
         <span>© Copyright 2019 HomeNows</span>
      </div>
      <div class="col-lg-6 py-4">
         <ul class="list-inline footer-nav u-ff-dosis text-center text-lg-right">
            <li class="list-inline-item">
               <a class="text-uppercase u-fw-600 p-2" href="#">Home</a>
            </li>
            <li class="list-inline-item">
               <a class="text-uppercase u-fw-600 p-2" href="#">Blog</a>
            </li>
            <li class="list-inline-item">
               <a class="text-uppercase u-fw-600 p-2" href="#">About</a>
            </li>
            <li class="list-inline-item">
               <a class="text-uppercase u-fw-600 p-2" href="#">Locations</a>
            </li>
            <li class="list-inline-item">
               <a class="text-uppercase u-fw-600 p-2" href="#">Contact</a>
            </li>
         </ul>
      </div>
   </div>
</div>
</footer>

app/views/layouts/_navigation.html.erb
<header class="header header-shrink header-inverse fixed-top">
         <div class="container">
            <nav class="navbar navbar-expand-lg px-md-0">
               <a class="navbar-brand" href="/">
               <span class="logo-default">
               <h2 class="logo-brand-color">HomeNows</h2>
               </span>
               </a>
               <button class="navbar-toggler p-0" data-toggle="collapse" data-target="#navbarNav">
                  <div class="hamburger hamburger--spin js-hamburger">
                     <div class="hamburger-box">
                        <div class="hamburger-inner"></div>
                     </div>
                  </div>
               </button>
               <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item active">
                        <button type="submit" class="btn nav-link ">
                           <%= link_to 'HOME', root_path %>        
                        </button>
                     </li>
                     <li class="nav-item">
                        <button type="submit" class="btn nav-link ">
                           <%= link_to 'ABOUT', about_path %>        
                        </button>
                     </li>
                     <li class="nav-item">
                        <button type="submit" class="btn nav-link ">
                           <%= link_to 'RECYCLING', recycling_path %>        
                        </button>
                     </li>
                     <li class="nav-item">
                        <button type="submit" class="btn nav-link ">
                           <%= link_to 'LIFESTYLE', lifestyle_path %>        
                        </button>
                     </li>
                     <li class="nav-item nav-link btn btn btn-rounded btn-green u-w-160 ml-lg-4 text-capitalize">
                     <% if current_user %>
                     <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                     <%else%>
                     <%= link_to 'Sign in', new_user_session_path %>
                     <% end %>
                     </li>
                  </ul>
               </div>
            </nav>
         </div>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <meta name="description" content="A complete landing page solution for any business">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>HOMENOWS | A lifestyle coompany.</title>
      
    <!-- Favicon -->
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
  <%= render 'layouts/alerts' %>
  <!-- Menu Partials -->
  <%= render 'layouts/navigation' %>
  
   <%= yield %>
  
  <!-- Footer Partials -->
  <%= render 'layouts/footer' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>